import Head from 'next/head';

export default function HeadMeta() {
  return (
    <Head>
      <title>인자강</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="initial-scale=1.0; maximum-scale=1.0; minimum-scale=1.0; user-scalable=no;" />
      <meta name="keywords" content="면접, 자소서, 가상면접, 면접 시뮬레이션, 자소서첨삭" />
      <meta name="Description" content="안녕하세요 자소서 첨삭 커뮤니티와 면접 시뮬레이션을 제공합니다.." />
      <meta httpEquiv="Subject" content="가상 면접 공간" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
